language: python

python:
  - 3.7

env:
  global:
    - secure: "<encrypted MYPYPI_USER=username>"
    - secure: "<encrypted MYPYPI_PASS=p@ssword>"

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run pytest tests/
