[tool.poetry]
name = "py-de-familia"
version = "0.1.0"
description = "CLI deliciosa"
authors = ["augustoliks <carlos.santos110@fatec.sp.gov.br>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
